name: Docker Builds

on:
  push:
    branches: ['*']

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: itshaydendev/php7-laravel
          dockerfile: 73.Dockerfile
